# Generated by Django 4.2 on 2023-12-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='asdasd', upload_to='users/avatars', verbose_name='Аватарка'),
            preserve_default=False,
        ),
    ]
