# Generated by Django 4.2 on 2023-12-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shifts',
            field=models.ManyToManyField(null=True, to='authentication.shift', verbose_name='Смены'),
        ),
    ]
