# Generated by Django 4.2 on 2023-12-17 17:09

import authentication.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_userrole_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=authentication.models.UserRole.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='authentication.userrole', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shifts',
            field=models.ManyToManyField(null=True, to='authentication.shift', verbose_name='Смены'),
        ),
    ]
