# Generated by Django 4.2 on 2023-12-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_userrole_options_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shifts',
            field=models.ManyToManyField(blank=True, to='authentication.shift', verbose_name='Смены'),
        ),
    ]
